---
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - binary
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'

dockers_v2:
  - images:
      - 'ghcr.io/{{ .Env.GITHUB_REPOSITORY }}'
    tags:
      - '{{ if not (or .IsNightly .IsSnapshot) }}v{{ .Version }}{{ end }}'
      - '{{ if or .IsNightly .IsSnapshot }}{{ .Version }}{{ end }}'
    labels:
      org.opencontainers.image.description: 'Masscan prometheus exporter'
      org.opencontainers.image.created: '{{ .Date }}'
      org.opencontainers.image.name: '{{ .ProjectName }}'
      org.opencontainers.image.revision: '{{ .FullCommit }}'
      org.opencontainers.image.version: '{{ .Version }}'
      org.opencontainers.image.source: '{{ .GitURL }}'
    platforms:
      - linux/amd64
      - linux/arm64
