{
 "title": "Masscan",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "jobs",
    "label": "Jobs",
    "query": {
     "query": "label_values(masscan_scrape_in_progress,job)"
    }
   },
   {
    "name": "collectors",
    "label": "Collectors",
    "query": {
     "query": "label_values(masscan_scrape_in_progress{job=~\"$jobs\"},collector)"
    }
   },
   {
    "name": "ips",
    "label": "IPs",
    "query": {
     "query": "label_values(masscan_ports_open{job=~\"$jobs\", collector=~\"$collectors\"},ip)"
    }
   },
   {
    "name": "ports",
    "label": "Ports",
    "query": {
     "query": "label_values(masscan_ports_open{job=~\"$jobs\", collector=~\"$ips|$collectors\", ip=~\"$ips\"},port)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ports open by job",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (collector) (masscan_ports_open{job=~\"$jobs\", collector=~\"$collectors\", ip=~\"$ips\", port=~\"$ports\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hosts by port",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "count by (port) (masscan_ports_open{job=~\"$jobs\", collector=~\"$collectors\", ip=~\"$ips\", port=~\"$ports\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports open by ip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (ip) (masscan_ports_open{job=~\"$jobs\", collector=~\"$collectors\", ip=~\"$ips\", port=~\"$ports\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports open by proto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count by (proto) (masscan_ports_open{job=~\"$jobs\", collector=~\"$collectors\", ip=~\"$ips\", port=~\"$ports\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ports for $collectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "collectors" },
  {
   "title": "Ports open by ip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "count by (ip) (masscan_ports_open{job=~\"$jobs\", collector=~\"$collectors\", ip=~\"$ips\", port=~\"$ports\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports open",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "count by (port) (masscan_ports_open{job=~\"$jobs\", collector=~\"$collectors\", ip=~\"$ips\", port=~\"$ports\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports open by proto",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "count by (proto) (masscan_ports_open{job=~\"$jobs\", collector=~\"$collectors\", ip=~\"$ips\", port=~\"$ports\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Scrape Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "Successful scrapes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (collector) (masscan_scrape_collector_success)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (collector) (masscan_scrape_in_progress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last scrape start time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (collector) (time() - masscan_scrape_start_time)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (collector) (masscan_scrape_seconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Received Packets by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_receive_packets_total{pod=~\"$jobs.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Transmitted Packets by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_network_transmit_packets_total{pod=~\"$jobs.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}